# Generated by Django 4.1.7 on 2023-03-06 08:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, default='Admin', max_length=30, verbose_name='Name')),
                ('user_id', models.CharField(max_length=30, unique=True, verbose_name='User ID in Telegram')),
                ('admin', models.BooleanField(default=False, verbose_name='If user admin true/else false')),
                ('admin_leverage', models.PositiveIntegerField(default=10, verbose_name='Admin default leverage')),
                ('balance', models.CharField(default=10, max_length=5, verbose_name='Balance allocated for order')),
                ('api_key', models.CharField(blank=True, max_length=265, verbose_name='api_key')),
                ('api_secret', models.CharField(blank=True, max_length=265, verbose_name='api_secret')),
                ('bot_token', models.CharField(max_length=255, verbose_name='Token bot telegram')),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_trader', models.CharField(max_length=25, verbose_name='NAME Trader')),
                ('symbol', models.CharField(max_length=15, verbose_name='Symbol')),
                ('side', models.CharField(default='none', max_length=55, verbose_name='SIDE')),
                ('size', models.CharField(max_length=55, verbose_name='Size')),
                ('entry_price', models.CharField(max_length=55, verbose_name='Entry Price')),
                ('mark_price', models.CharField(max_length=55, verbose_name='Mark Price')),
                ('pnl', models.CharField(max_length=55, verbose_name='PNL (ROE %)')),
                ('roe', models.CharField(max_length=55, verbose_name='ROE')),
                ('date', models.CharField(max_length=55, verbose_name='TIME')),
                ('is_active', models.BooleanField(default=True)),
                ('upd', models.CharField(max_length=86, verbose_name='Update time order')),
            ],
        ),
        migrations.CreateModel(
            name='Traders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Name')),
                ('link', models.CharField(max_length=255, verbose_name='LINK TO PROFILE')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=25, verbose_name='Name User')),
                ('user_id', models.CharField(max_length=30, unique=True, verbose_name='User ID in Telegram')),
                ('subs_date_end', models.DateField(blank=True, null=True, verbose_name='Subscription end')),
                ('subs_active', models.BooleanField(default=False, verbose_name='If the subscription is active then true if not false')),
                ('leverage', models.PositiveIntegerField(default=10, verbose_name='default leverage')),
                ('percent_balance', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Percent allocated for order')),
                ('api_key', models.CharField(max_length=350, verbose_name='Exchange api key')),
                ('api_secret', models.CharField(max_length=350, verbose_name='Exchange api secret')),
                ('subscription_type', models.CharField(choices=[('Ordinary', 'Ordinary'), ('Standard', 'Standard'), ('VIP', 'VIP')], default='Ordinary', max_length=10, verbose_name='Subscription type')),
                ('exchange', models.CharField(choices=[('Binance', 'Binance'), ('Bybit', 'Bybit')], default='Binance', max_length=10, verbose_name='Exchange')),
                ('traders', models.ManyToManyField(to='Bot.traders')),
            ],
        ),
    ]
