# Generated by Django 4.1.7 on 2023-03-06 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'permissions': [('set_published_status', 'Can set the status of the post to either publish or not')]},
        ),
    ]
