# Generated by Django 4.1.7 on 2023-03-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0003_family_alter_users_options_alter_users_traders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='traders',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_staff': True}, related_name='users', to='Bot.traders'),
        ),
        migrations.DeleteModel(
            name='Family',
        ),
    ]
