# Generated by Django 4.1.7 on 2023-03-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0008_alter_users_traders_delete_userfollowing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='traders',
        ),
        migrations.AddField(
            model_name='traders',
            name='traders',
            field=models.ManyToManyField(blank=True, null=True, related_name='followers', to='Bot.users'),
        ),
    ]
