# Generated by Django 4.1.7 on 2023-03-07 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0009_remove_users_traders_traders_traders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traders',
            old_name='traders',
            new_name='users_f',
        ),
    ]
