# Generated by Django 4.1.7 on 2023-03-07 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0010_rename_traders_traders_users_f'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traders',
            name='users_f',
        ),
        migrations.AlterField(
            model_name='signal',
            name='name_trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bot.traders'),
        ),
    ]
