# Generated by Django 4.1.7 on 2023-03-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0013_users_language_alter_users_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='exchange',
            field=models.CharField(choices=[('Not_connect', 'Binance'), ('Binance', 'Binance'), ('Bybit', 'Bybit')], default='Not_connect', max_length=25, verbose_name='Exchange'),
        ),
        migrations.AlterField(
            model_name='users',
            name='subscription_type',
            field=models.CharField(choices=[('Free', 'Free'), ('Ordinary', 'Ordinary'), ('Standard', 'Standard'), ('VIP', 'VIP')], default='Free', max_length=25, verbose_name='Subscription type'),
        ),
    ]
