# Generated by Django 4.1.7 on 2023-03-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0015_signal_status_alter_users_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='traders_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of traders the user is subscribed to'),
        ),
    ]
