# Generated by Django 4.1.7 on 2023-03-11 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0016_users_traders_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='referral',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Bot.users'),
            preserve_default=False,
        ),
    ]
