# Generated by Django 4.1.7 on 2023-03-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0020_alter_users_subscription_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='subscription_type',
            field=models.CharField(choices=[('Free', 'Free'), ('Basic', 'Basic'), ('Standard', 'Standard'), ('VIP', 'VIP')], default='Free', max_length=25, verbose_name='Subscription type'),
        ),
    ]
