# Generated by Django 4.1.7 on 2023-04-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0022_remove_users_traders_count_signal_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traders',
            name='is_active',
            field=models.BooleanField(default=True, help_text='If the check box is active, the trader"s trades are copied ', verbose_name='Active'),
        ),
    ]
