# Generated by Django 4.1.7 on 2023-04-18 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0025_rename_admin_admin_subs_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='admin_leverage',
            new_name='leverage',
        ),
    ]
